/// Flutter icons NotifIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotifIcons
///      fonts:
///       - asset: fonts/NotifIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NotifIcons {
  NotifIcons._();

  static const _kFontFam = 'NotifIcons';

  static const IconData class_icon =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData principal_s_desk =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData department =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData administrative =
      const IconData(0xf0f7, fontFamily: _kFontFam);
}
